stages:

 - build-push
 - deploy

image: docker:19.03.12
variables:
 DOCKER_HOST: tcp://docker:2375/
 DOCKER_TLS_CERTDIR: ""
 DOCKER_IMAGE_NAME: ${CI_PROJECT_NAME}
services:
 - docker:19.03.12-dind

build-push:
 stage: build-push
 before_script:
   - docker info
   - echo "$SERVICE_ACCOUNT_KEY" > key.json
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 script:
   - docker build --tag $REGISTRY_HOSTNAME/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
   - docker push $REGISTRY_HOSTNAME/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA

deploy:
 stage: deploy
 image: google/cloud-sdk
 script:
# Authenticate with GKE
   - echo "$SERVICE_ACCOUNT_KEY" > key.json
   - gcloud auth activate-service-account --key-file=key.json
   - gcloud config set project GCP_PROJECT_NAME
   - gcloud config set container/cluster GKE_CLUSTER_NAME
   - gcloud config set compute/zone asia-south1-c
   - gcloud container clusters get-credentials autopilot-cluster-1 --zone us-central1 --project goapi
   - sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" ./k8s/deployment.yaml
   - kubectl apply -f k8s