apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dep-svc-goapi
  name: dep-svc-goapi
spec:
  ports:
  - name: dep-port
    port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 30000
  selector:
    app: dep-goapi
  type: NodePort
status:
  loadBalancer: {}
